[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.2"

[[constraint]]
  name = "github.com/oklog/oklog"
  version = "0.3.2"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
